# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for LIGHT STREAM SWITCH APP
# Builds StreamSwitch.exe from app_launcher.py

from PyInstaller.utils.hooks import (
    collect_submodules,
    collect_data_files,
)

a = Analysis(
    ['app_launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('pymod', 'pymod'),
        ('templates', 'templates'),
        ('static', 'static'),
        ('data', 'data'),
        ('tools', 'tools'),
        ('bible.py', '.'),
        ('live_input.py', '.'),
        ('broadcast_push.py', '.'),
        ('broadcast_wiring.py', '.'),
        ('outputs_config.py', '.'),
        ('screen_config_routes.py', '.'),
        ('usb_program.py', '.'),
        ('stream_server.py', '.'),
        ('server_version.py', '.'),
        ('audio_monitor.py', '.'),
        ('audio_monitor_server.py', '.'),
        ('app.version', 'pymod'),
    ] + collect_data_files('pyaudiowpatch') + collect_data_files('pycaw'),
    hiddenimports=[
        'eventlet.hubs.epolls',
        'eventlet.hubs.kqueue',
        'eventlet.hubs.poll',
        'eventlet.hubs.selects',
        'eventlet.green.thread',
        'eventlet.green.threading',
        'eventlet.websocket',
        'engineio.async_drivers.threading',
        'engineio.async_drivers.eventlet',
        'socketio',
        'flask_limiter',
        'flask_limiter.util',
        'dotenv',
        'live_input',
        'stream_server',
        'server_version',
        'bible',
        'broadcast_push',
        'broadcast_wiring',
        'outputs_config',
        'screen_config_routes',
        'usb_program',
        'comtypes',
        'pygrabber',
        'pygrabber.dshow_graph',
        'cv2',
        'numpy',
        'sqlite3',
        'asyncio',
        'ctypes',
        'websockets',
        'wsproto',
        'bidict',
        'requests',
        'urllib3',
        'certifi',
        'idna',
        'charset_normalizer',
        'mutagen',
        'audio_monitor',
        'audio_monitor_server',
        'pyaudiowpatch',
        '_portaudiowpatch',
        'pycaw',
        'pycaw.pycaw',
        'pycaw.utils',
        'pycaw.constants',
        'pycaw.callbacks',
        'pycaw.api',
        'pycaw.api.mmdeviceapi',
        'pycaw.api.audioclient',
        'pycaw.api.endpointvolume',
        'pycaw.api.audiopolicy',
        'comtypes.stream',
        'comtypes.client',
        'comtypes.client._generate',
        'mss',
        'serial',
        'serial.tools',
        'serial.tools.list_ports',
    ] + collect_submodules('dns') + collect_submodules('websockets') + collect_submodules('requests') + collect_submodules('wsproto') + collect_submodules('comtypes') + collect_submodules('pyaudiowpatch') + collect_submodules('pycaw'),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='StreamSwitch',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='file_version_info.txt',
    uac_admin=False,
)
